version: '3.4'

services:
  churchsite:
    image: churchsite
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
      - AZURE_ACCOUNT_KEY=${AZURE_ACCOUNT_KEY}
      - AZURE_CONTAINER=${AZURE_CONTAINER}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: python /app/manage.py runserver 0.0.0.0:8000